"""C2 — Copiloto: definición y dispatcher de tools de LECTURA.

Las 7 tools de escritura (create_contact, create_deal, etc.) van en C3 con
confirmación obligatoria. Este archivo solo expone operaciones sin side-effects.

Tool-use format: nativo Anthropic SDK 0.104.x
  name, description, input_schema (JSON Schema)
"""
from __future__ import annotations

import json
import uuid
from datetime import date, datetime, timezone
from typing import Any

from sqlalchemy import and_, func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.activity import Activity
from app.models.agent import AgentSuggestion
from app.models.ai_memory import AIEntityContext, AIMemoryEvent
from app.models.deal import Deal
from app.models.finance import Expense
from app.models.lead import Lead
from app.models.pipeline import PipelineStage
from app.models.tenant import Tenant
from app.models.user import User, UserRole
from app.services.profitability import (
    get_current_month_goal,
    get_tenant_profitability,
    get_tenant_run_rate,
    get_user_profitability,
    get_user_run_rate,
)

# ── Role guard ────────────────────────────────────────────────────────────────

_OWNER_ROLES = (UserRole.OWNER, UserRole.PLATFORM_OWNER)

# ── Tool catalog (Anthropic native format) ────────────────────────────────────

COPILOT_READ_TOOLS: list[dict[str, Any]] = [
    {
        "name": "get_pipeline_status",
        "description": (
            "Returns the current sales pipeline: number of active deals and total MXN value "
            "per stage, ordered from first to last stage. Use this when the user asks about "
            "their pipeline, how many deals they have, or what's in each stage."
        ),
        "input_schema": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
    {
        "name": "search_contacts",
        "description": (
            "Searches contacts (leads) by name or WhatsApp phone number. "
            "Returns basic info: id, name, phone, status, assigned agent. "
            "Use when the user asks about a specific client or contact."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Name fragment or phone number to search for",
                },
                "limit": {
                    "type": "integer",
                    "description": "Max results to return (default 10, max 20)",
                    "default": 10,
                },
            },
            "required": ["query"],
        },
    },
    {
        "name": "get_contact_context",
        "description": (
            "Returns AI memory context for a specific contact: summary, key facts, "
            "sentiment, urgency score, and recent memory events. "
            "Requires a contact_id (UUID). Use after search_contacts to get deep context."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "contact_id": {
                    "type": "string",
                    "description": "UUID of the contact (lead)",
                },
            },
            "required": ["contact_id"],
        },
    },
    {
        "name": "get_my_tasks",
        "description": (
            "Returns pending tasks for the current user: title, kind (cobro, cotizacion, etc.), "
            "due date, overdue flag, and associated contact/deal. "
            "Use when the user asks about their pending tasks or activities."
        ),
        "input_schema": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
    {
        "name": "get_my_suggestions",
        "description": (
            "Returns active AI suggestions (follow-up recommendations, pipeline alerts, etc.) "
            "generated by the Walix agent for the current user. "
            "Use when the user asks for recommendations or what they should do next."
        ),
        "input_schema": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
    {
        "name": "get_my_deals",
        "description": (
            "Returns a list of deals (opportunities). "
            "scope='mine' shows only deals owned by the current user; "
            "scope='tenant' shows all deals in the tenant. "
            "Use when asked about deals, opportunities, or sales."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "scope": {
                    "type": "string",
                    "enum": ["mine", "tenant"],
                    "description": "mine = only user's deals; tenant = all tenant deals",
                    "default": "mine",
                },
                "include_won": {
                    "type": "boolean",
                    "description": "Include won deals (default false = active only)",
                    "default": False,
                },
                "include_lost": {
                    "type": "boolean",
                    "description": "Include lost deals (default false = active only)",
                    "default": False,
                },
            },
            "required": [],
        },
    },
    {
        "name": "get_profitability",
        "description": (
            "Returns profitability analytics: revenue, expenses, profit, profit % and label "
            "(green/yellow/orange/red). scope='tenant' for overall; scope='user' for the current user. "
            "Use when asked about profit margin, rentabilidad, or financial health."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "scope": {
                    "type": "string",
                    "enum": ["tenant", "user"],
                    "default": "tenant",
                },
                "year": {"type": "integer", "description": "Year (default: current)"},
                "month": {"type": "integer", "description": "Month 1-12 (default: current)"},
            },
            "required": [],
        },
    },
    {
        "name": "get_run_rate",
        "description": (
            "Returns run-rate analytics: won revenue, projected month-end revenue, "
            "goal amount, % of goal, gap, and recommendations. "
            "scope='tenant' for overall; scope='user' for the current user. "
            "Use when asked about run rate, sales projection, or monthly progress."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "scope": {
                    "type": "string",
                    "enum": ["tenant", "user"],
                    "default": "tenant",
                },
                "year": {"type": "integer", "description": "Year (default: current)"},
                "month": {"type": "integer", "description": "Month 1-12 (default: current)"},
            },
            "required": [],
        },
    },
    {
        "name": "get_expenses_summary",
        "description": (
            "Returns a summary of confirmed expenses for a period: "
            "total by kind (fijo/variable), total overall, and top expense categories. "
            "Use when asked about expenses, gastos, or costs."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "year": {"type": "integer", "description": "Year (default: current)"},
                "month": {"type": "integer", "description": "Month 1-12 (default: current)"},
            },
            "required": [],
        },
    },
    {
        "name": "get_monthly_goal",
        "description": (
            "Returns the current global monthly sales goal for the tenant: "
            "target amount, period, and whether it's active. "
            "Use when asked about the monthly goal or meta mensual."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "year": {"type": "integer", "description": "Year (default: current)"},
                "month": {"type": "integer", "description": "Month 1-12 (default: current)"},
            },
            "required": [],
        },
    },
    {
        "name": "get_team_performance",
        "description": (
            "Returns performance data for all active team members: won revenue, run rate, "
            "run rate % of goal, expenses, and profit margin per person. "
            "Only available to OWNER and PLATFORM_OWNER roles. "
            "Use when asked about team performance or individual seller stats."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "year": {"type": "integer", "description": "Year (default: current)"},
                "month": {"type": "integer", "description": "Month 1-12 (default: current)"},
            },
            "required": [],
        },
    },
]

# ── Serialization helper ───────────────────────────────────────────────────────

def _serial(obj: Any) -> Any:
    """json default= handler for types not natively serializable."""
    if isinstance(obj, uuid.UUID):
        return str(obj)
    if isinstance(obj, (date, datetime)):
        return obj.isoformat()
    return str(obj)


def _jsonable(obj: Any) -> Any:
    """Convert a dict/list to fully JSON-serializable using _serial."""
    return json.loads(json.dumps(obj, default=_serial))

# ── Tool dispatcher ───────────────────────────────────────────────────────────

async def execute_read_tool(
    name: str,
    args: dict[str, Any],
    user: User,
    tenant: Tenant,
    db: AsyncSession,
) -> dict[str, Any]:
    """Dispatch a tool call to the appropriate service function.

    All results are JSON-serializable (UUID/Decimal/date converted).
    Tenant boundary is enforced — never returns data from another tenant.
    Returns a plain dict; the engine serializes it for the tool_result block.
    """
    today = date.today()
    year: int = int(args.get("year") or today.year)
    month: int = int(args.get("month") or today.month)

    # ── get_pipeline_status ────────────────────────────────────────────────────
    if name == "get_pipeline_status":
        rows = (
            await db.execute(
                select(
                    PipelineStage.name,
                    PipelineStage.order_index,
                    func.count(Deal.id).label("deal_count"),
                    func.coalesce(func.sum(Deal.amount), 0).label("total_value"),
                )
                .outerjoin(
                    Deal,
                    and_(
                        Deal.pipeline_stage_id == PipelineStage.id,
                        Deal.is_won.is_(False),
                        Deal.is_lost.is_(False),
                    ),
                )
                .where(
                    PipelineStage.tenant_id == user.tenant_id,
                    PipelineStage.is_archived.is_(False),
                    PipelineStage.is_won.is_(False),
                    PipelineStage.is_lost.is_(False),
                )
                .group_by(
                    PipelineStage.id,
                    PipelineStage.name,
                    PipelineStage.order_index,
                )
                .order_by(PipelineStage.order_index)
            )
        ).fetchall()

        stages = [
            {
                "stage": row.name,
                "deal_count": row.deal_count,
                "total_value_mxn": float(row.total_value),
            }
            for row in rows
        ]
        total_value = sum(s["total_value_mxn"] for s in stages)
        total_deals = sum(s["deal_count"] for s in stages)
        return {
            "stages": stages,
            "total_active_deals": total_deals,
            "total_pipeline_value_mxn": total_value,
        }

    # ── search_contacts ────────────────────────────────────────────────────────
    if name == "search_contacts":
        query = str(args.get("query", "")).strip()
        limit = min(int(args.get("limit", 10)), 20)
        if not query:
            return {"contacts": [], "count": 0}

        rows = (
            await db.execute(
                select(Lead)
                .where(
                    Lead.tenant_id == user.tenant_id,
                    Lead.deleted_at.is_(None),
                    or_(
                        Lead.name.ilike(f"%{query}%"),
                        Lead.last_name.ilike(f"%{query}%"),
                        Lead.wa_phone.ilike(f"%{query}%"),
                    ),
                )
                .limit(limit)
            )
        ).scalars().all()

        contacts = [
            {
                "id": str(lead.id),
                "name": " ".join(
                    filter(None, [lead.name, lead.last_name])
                ) or "Sin nombre",
                "wa_phone": lead.wa_phone,
                "status": lead.status.value if lead.status else None,
                "assigned_to": str(lead.assigned_to) if lead.assigned_to else None,
            }
            for lead in rows
        ]
        return {"contacts": contacts, "count": len(contacts)}

    # ── get_contact_context ────────────────────────────────────────────────────
    if name == "get_contact_context":
        try:
            contact_id = uuid.UUID(str(args.get("contact_id", "")))
        except (ValueError, AttributeError):
            return {"error": "contact_id inválido"}

        ctx_row = (
            await db.execute(
                select(AIEntityContext).where(
                    AIEntityContext.tenant_id == user.tenant_id,
                    AIEntityContext.entity_type == "contact",
                    AIEntityContext.entity_id == contact_id,
                )
            )
        ).scalar_one_or_none()

        events_rows = (
            await db.execute(
                select(AIMemoryEvent)
                .where(
                    AIMemoryEvent.tenant_id == user.tenant_id,
                    AIMemoryEvent.entity_id == contact_id,
                )
                .order_by(AIMemoryEvent.created_at.desc())
                .limit(10)
            )
        ).scalars().all()

        return {
            "contact_id": str(contact_id),
            "context": {
                "summary": ctx_row.context_summary if ctx_row else None,
                "key_facts": ctx_row.key_facts if ctx_row else [],
                "sentiment": ctx_row.sentiment if ctx_row else "unknown",
                "urgency_score": ctx_row.urgency_score if ctx_row else 0,
                "last_interaction": _serial(ctx_row.last_interaction) if ctx_row else None,
            },
            "recent_events": [
                {
                    "event_type": e.event_type,
                    "data": e.event_data,
                    "occurred_at": _serial(e.created_at),
                }
                for e in events_rows
            ],
        }

    # ── get_my_tasks ───────────────────────────────────────────────────────────
    if name == "get_my_tasks":
        now_utc = datetime.now(timezone.utc)
        rows = (
            await db.execute(
                select(Activity, Lead.name, Lead.last_name)
                .join(Lead, Activity.lead_id == Lead.id)
                .where(
                    Activity.tenant_id == user.tenant_id,
                    Activity.activity_type == "task",
                    Activity.completed_at.is_(None),
                    or_(
                        Activity.assignee_id == user.id,
                        and_(
                            Activity.assignee_id.is_(None),
                            Activity.created_by == user.id,
                        ),
                    ),
                )
                .order_by(Activity.due_date.asc())
                .limit(20)
            )
        ).fetchall()

        def _is_overdue(due: datetime | None) -> bool:
            if due is None:
                return False
            aware = due if due.tzinfo else due.replace(tzinfo=timezone.utc)
            return aware < now_utc

        tasks = [
            {
                "id": str(row.Activity.id),
                "title": row.Activity.title,
                "task_kind": row.Activity.task_kind,
                "due_date": _serial(row.Activity.due_date),
                "overdue": _is_overdue(row.Activity.due_date),
                "contact_name": " ".join(
                    filter(None, [row[1], row[2]])
                ) or "Sin nombre",
                "lead_id": str(row.Activity.lead_id),
            }
            for row in rows
        ]
        overdue_count = sum(1 for t in tasks if t["overdue"])
        return {
            "tasks": tasks,
            "total": len(tasks),
            "overdue": overdue_count,
        }

    # ── get_my_suggestions ─────────────────────────────────────────────────────
    if name == "get_my_suggestions":
        rows = (
            await db.execute(
                select(AgentSuggestion)
                .where(
                    AgentSuggestion.tenant_id == user.tenant_id,
                    AgentSuggestion.status == "suggested",
                    AgentSuggestion.expires_at > func.now(),
                    or_(
                        AgentSuggestion.target_user_id == user.id,
                        AgentSuggestion.target_user_id.is_(None),
                    ),
                )
                .order_by(AgentSuggestion.created_at.desc())
                .limit(10)
            )
        ).scalars().all()

        return {
            "suggestions": [
                {
                    "id": str(s.id),
                    "agent_type": s.agent_type,
                    "text": s.suggestion_text,
                    "trigger": s.trigger_description,
                    "entity_type": s.entity_type,
                    "entity_id": str(s.entity_id) if s.entity_id else None,
                    "expires_at": _serial(s.expires_at),
                }
                for s in rows
            ],
            "count": len(rows),
        }

    # ── get_my_deals ───────────────────────────────────────────────────────────
    if name == "get_my_deals":
        scope = str(args.get("scope", "mine"))
        include_won = bool(args.get("include_won", False))
        include_lost = bool(args.get("include_lost", False))

        filters = [Deal.tenant_id == user.tenant_id]
        if scope == "mine":
            filters.append(Deal.owner_id == user.id)

        status_filters = []
        if not include_won and not include_lost:
            # Default: active only
            filters.append(Deal.is_won.is_(False))
            filters.append(Deal.is_lost.is_(False))
        else:
            if include_won:
                status_filters.append(Deal.is_won.is_(True))
            if include_lost:
                status_filters.append(Deal.is_lost.is_(True))
            if status_filters:
                filters.append(or_(*status_filters))

        rows = (
            await db.execute(
                select(Deal, PipelineStage.name.label("stage_name"))
                .join(PipelineStage, Deal.pipeline_stage_id == PipelineStage.id)
                .where(*filters)
                .order_by(Deal.updated_at.desc())
                .limit(20)
            )
        ).fetchall()

        deals = [
            {
                "id": str(row.Deal.id),
                "title": row.Deal.title,
                "amount_mxn": float(row.Deal.amount),
                "stage": row.stage_name,
                "is_won": row.Deal.is_won,
                "is_lost": row.Deal.is_lost,
                "deal_type": row.Deal.deal_type,
                "expected_close": _serial(row.Deal.expected_close_date),
                "lead_id": str(row.Deal.lead_id),
            }
            for row in rows
        ]
        total_value = sum(d["amount_mxn"] for d in deals if not d["is_won"] and not d["is_lost"])
        return {
            "deals": deals,
            "count": len(deals),
            "active_pipeline_value_mxn": total_value,
        }

    # ── get_profitability ──────────────────────────────────────────────────────
    if name == "get_profitability":
        scope = str(args.get("scope", "tenant"))
        if scope == "user":
            result = await get_user_profitability(tenant, user.id, year, month, db)
        else:
            result = await get_tenant_profitability(tenant, year, month, db)
        return _jsonable(result)

    # ── get_run_rate ───────────────────────────────────────────────────────────
    if name == "get_run_rate":
        scope = str(args.get("scope", "tenant"))
        if scope == "user":
            result = await get_user_run_rate(tenant, user.id, year, month, db)
        else:
            result = await get_tenant_run_rate(tenant, year, month, db)
        return _jsonable(result)

    # ── get_expenses_summary ───────────────────────────────────────────────────
    if name == "get_expenses_summary":
        kind_rows = (
            await db.execute(
                select(Expense.kind, func.sum(Expense.amount).label("total"))
                .where(
                    Expense.tenant_id == user.tenant_id,
                    Expense.status == "confirmed",
                    func.extract("year", Expense.incurred_at) == year,
                    func.extract("month", Expense.incurred_at) == month,
                )
                .group_by(Expense.kind)
            )
        ).fetchall()

        by_kind = {row.kind: float(row.total) for row in kind_rows}
        total = sum(by_kind.values())

        return {
            "year": year,
            "month": month,
            "by_kind": by_kind,
            "total_mxn": total,
            "fijo_mxn": by_kind.get("fijo", 0.0),
            "variable_mxn": by_kind.get("variable", 0.0),
        }

    # ── get_monthly_goal ───────────────────────────────────────────────────────
    if name == "get_monthly_goal":
        goal = await get_current_month_goal(user.tenant_id, year, month, db)
        if goal is None:
            return {
                "year": year,
                "month": month,
                "goal_set": False,
                "amount_mxn": None,
                "message": "No hay meta mensual configurada para este periodo.",
            }
        return {
            "year": year,
            "month": month,
            "goal_set": True,
            "amount_mxn": float(goal.amount),
            "is_draft": goal.is_draft,
        }

    # ── get_team_performance ───────────────────────────────────────────────────
    if name == "get_team_performance":
        if user.role not in _OWNER_ROLES:
            return {
                "error": (
                    "Sin acceso. Solo el propietario puede ver el rendimiento "
                    "individual del equipo."
                )
            }

        team_users = (
            await db.execute(
                select(User).where(
                    User.tenant_id == user.tenant_id,
                    User.is_active.is_(True),
                    User.role != UserRole.PLATFORM_OWNER,
                )
            )
        ).scalars().all()

        members = []
        for u in team_users:
            rr = await get_user_run_rate(tenant, u.id, year, month, db)
            prof = await get_user_profitability(tenant, u.id, year, month, db)
            members.append(
                {
                    "user_id": str(u.id),
                    "name": u.name,
                    "role": u.role.value,
                    "won_revenue_mxn": rr["won_revenue"],
                    "run_rate_mxn": rr["run_rate"],
                    "user_goal_mxn": rr.get("user_goal"),
                    "pct_of_goal": rr.get("pct_of_goal"),
                    "expenses_mxn": prof["expenses"],
                    "profit_mxn": prof["profit"],
                    "profit_pct": prof["profit_pct"],
                    "label": prof["label"],
                }
            )

        members.sort(key=lambda m: m["won_revenue_mxn"], reverse=True)
        return {
            "year": year,
            "month": month,
            "team": members,
            "count": len(members),
        }

    # ── Unknown tool ───────────────────────────────────────────────────────────
    return {"error": f"Tool '{name}' no reconocida"}
